# Generated by Django 2.0.2 on 2018-02-14 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featuredimg',
            field=models.FileField(blank=True, null=True, upload_to='featured/%Y/%m/%d/', verbose_name='特色图像'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_description',
            field=models.TextField(blank=True, null=True, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_keywords',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='关键词'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_sourcelink',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='来源链接'),
        ),
    ]
