# Generated by Django 2.0.2 on 2018-06-01 02:35

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='姓名')),
                ('author_nickname', models.CharField(max_length=100, verbose_name='作者')),
                ('author_country', models.CharField(max_length=100, verbose_name='国家')),
                ('author_desc', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='作者简介')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='发布日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '作者信息',
                'verbose_name_plural': '作者信息',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=250, verbose_name='书名')),
                ('book_isbn', models.CharField(max_length=50, verbose_name='ISBN')),
                ('book_version', models.CharField(blank=True, max_length=10, null=True, verbose_name='版本')),
                ('book_lang', models.CharField(blank=True, max_length=100, null=True, verbose_name='语言')),
                ('book_paper', models.CharField(blank=True, max_length=100, null=True, verbose_name='用纸')),
                ('book_size', models.BooleanField(choices=[(1, '64开'), (2, '42开'), (3, '36开'), (4, '32开'), (5, '24开'), (6, '20开'), (7, '16开'), (8, '12开'), (9, '8开'), (10, '6开'), (11, '4开'), (12, '对开')], default=4, verbose_name='开本')),
                ('book_packing', models.BooleanField(choices=[(1, '平装'), (2, '精装'), (3, '套装')], default=1, verbose_name='装帧')),
                ('book_able', models.BooleanField(choices=[(1, '显示'), (0, '不显示')], default=1, verbose_name='是否上架')),
                ('book_recommend', models.BooleanField(choices=[(0, '不推荐'), (1, '推荐')], default=1, verbose_name='是否推荐')),
                ('book_publish_year', models.CharField(choices=[(2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996), (1995, 1995), (1994, 1994), (1993, 1993), (1992, 1992), (1991, 1991), (1990, 1990), (1989, 1989), (1988, 1988), (1987, 1987), (1986, 1986), (1985, 1985), (1984, 1984), (1983, 1983), (1982, 1982), (1981, 1981), (1980, 1980), (1979, 1979), (1978, 1978), (1977, 1977), (1976, 1976), (1975, 1975), (1974, 1974), (1973, 1973), (1972, 1972), (1971, 1971)], default=2018, max_length=4)),
                ('book_pages', models.PositiveIntegerField(blank=True, null=True, verbose_name='页数')),
                ('book_words', models.PositiveIntegerField(blank=True, null=True, verbose_name='字数')),
                ('book_desc', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='书籍介绍')),
                ('book_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='目录')),
                ('book_preface', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='前言')),
                ('book_comments', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='书籍评价')),
                ('book_original_price', models.FloatField(verbose_name='原价')),
                ('book_sale_price', models.FloatField(verbose_name='优惠价')),
                ('book_sale_nums', models.PositiveIntegerField(blank=True, null=True, verbose_name='销售数量')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='发布日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookstore.Author', verbose_name='书籍作者')),
            ],
            options={
                'verbose_name': '书籍信息',
                'verbose_name_plural': '书籍信息',
            },
        ),
        migrations.CreateModel(
            name='BookCate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='发布日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookcate', to='bookstore.BookCate')),
            ],
            options={
                'verbose_name': '书籍分类',
                'verbose_name_plural': '书籍分类',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=100, verbose_name='出版社')),
                ('publisher_logo', models.FileField(blank=True, null=True, upload_to='logo/%Y/%m/%d/', verbose_name='出版社LOGO')),
                ('publisher_desc', models.CharField(max_length=200, verbose_name='出版社介绍')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='发布日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '出版社信息',
                'verbose_name_plural': '出版社信息',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookstore.Publisher', verbose_name='书籍出版社'),
        ),
    ]
