# Generated by Django 2.0.2 on 2018-06-02 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20180602_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='author', verbose_name='作者头像'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_recommend',
            field=models.BooleanField(choices=[(0, '正常'), (1, '推荐')], default=1, verbose_name='是否推荐'),
        ),
        migrations.AlterField(
            model_name='bookcate',
            name='is_recommend',
            field=models.BooleanField(choices=[(0, '正常'), (1, '推荐')], default=0, verbose_name='是否推荐'),
        ),
        migrations.AlterField(
            model_name='bookcate',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookcate', to='bookstore.BookCate', verbose_name='父级分类'),
        ),
    ]
