# Generated by Django 2.0.2 on 2018-06-01 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookstore', '0002_book_cate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookcomment_content', models.TextField(verbose_name='评论内容')),
                ('bookcomment_isopen', models.BooleanField(choices=[(1, '显示'), (0, '不显示')], default=1, verbose_name='是否显示')),
                ('bookcomment_thumbup', models.IntegerField(default=0, verbose_name='点赞数')),
                ('bookcomment_thumbdown', models.IntegerField(default=0, verbose_name='点踩数')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='发布日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Book', verbose_name='书籍')),
            ],
            options={
                'verbose_name': '文章评论',
                'verbose_name_plural': '管理文章评论',
            },
        ),
        migrations.CreateModel(
            name='BookImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookimg_title', models.CharField(max_length=255, null=True, verbose_name='标题')),
                ('bookimg_img', models.FileField(max_length=255, null=True, upload_to='', verbose_name='图片')),
                ('bookimg_thumburl', models.CharField(max_length=255, null=True, verbose_name='')),
                ('bookimg_commonurl', models.CharField(max_length=255, null=True)),
                ('bookimg_originurl', models.CharField(max_length=255, null=True)),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='发布日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Book', verbose_name='书籍')),
            ],
            options={
                'verbose_name': '文章图片',
                'verbose_name_plural': '管理文章图片',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nums', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='发布日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Book', verbose_name='书籍')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, null=True, verbose_name='昵称')),
                ('avatar', models.FileField(max_length=255, null=True, upload_to='', verbose_name='头像')),
                ('token', models.CharField(max_length=255, null=True)),
                ('openid', models.CharField(max_length=255, null=True)),
                ('qq', models.CharField(max_length=20, null=True, verbose_name='QQ')),
                ('mobile', models.CharField(max_length=20, null=True, verbose_name='手机')),
                ('sex', models.BooleanField(choices=[(1, '男'), (0, '女')], default=1, verbose_name='性别')),
                ('ip', models.GenericIPAddressField(null=True, verbose_name='IP')),
                ('birthday', models.DateField(null=True, verbose_name='生日')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='发布日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='客户')),
            ],
            options={
                'verbose_name': '客户信息',
                'verbose_name_plural': '客户信息',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods', models.CharField(max_length=250, verbose_name='商品')),
                ('status', models.BooleanField(choices=[(1, '未支付'), (2, '已支付'), (3, '已发货'), (4, '已完成'), (5, '退款中'), (6, '已退款')], default=1, verbose_name='订单状态')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='发布日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Customer', verbose_name='客户')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='bookcomment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Customer', verbose_name='客户'),
        ),
    ]
