# Generated by Django 2.0.2 on 2018-06-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20180602_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcate',
            name='color',
            field=models.CharField(max_length=10, null=True, verbose_name='主颜色'),
        ),
        migrations.AlterField(
            model_name='bookimg',
            name='bookimg_commonurl',
            field=models.CharField(max_length=255, null=True, verbose_name='常规尺寸'),
        ),
        migrations.AlterField(
            model_name='bookimg',
            name='bookimg_originurl',
            field=models.CharField(max_length=255, null=True, verbose_name='原图'),
        ),
        migrations.AlterField(
            model_name='bookimg',
            name='bookimg_thumburl',
            field=models.CharField(max_length=255, null=True, verbose_name='缩略图'),
        ),
        migrations.AlterField(
            model_name='bookimg',
            name='bookimg_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='标题'),
        ),
    ]
