# Generated by Django 2.0.2 on 2018-06-03 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_auto_20180602_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=200, null=True, verbose_name='邮箱'),
        ),
    ]
