# Generated by Django 2.0.2 on 2018-06-03 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.AlterField(
            model_name='customer',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='手机'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='openid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='qq',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='QQ'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
